### ISSUE TITLE
ошибка запуска 

### ISSUE THREAD

**Issue by EndrII** [QuasarApp/Hanoi-Towers#13]
nvidia proprietary driver
```
Qt: Session management error: None of the authentication protocols specified are supported
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Could not initialize GLX

```

messa driver (AMD):
```

Qt: Session management error: None of the authentication protocols specified are supported
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
Unrecognized OpenGL version
Unrecognized OpenGL version
```

**Comment by EndrII** [comment]
https://forum.snapcraft.io/t/build-snap-package-with-qml-in-ubuntu-17-10/4987

**Comment by EndrII** [comment]
https://forum.snapcraft.io/t/qt-dependencies/4879/11

**Comment by EndrII** [comment]
`/snap/hanoi-towers/x1/command-hanoi-towers.wrapper: 6: exec: /snap/hanoi-towers/x1/bin/hanoi-towers: not found
`

**Comment by EndrII** [comment]
``` yml
name: hanoi-towers
version: '1.4'
summary: Hanoi Towers Game
description: |
  The Hanoi Tower is one of the most popular puzzles of the 19th century. Three bars are given, on one of which eight rings are strung, the rings differ in size and lie smaller on larger ones. The problem is to transfer the pyramid from eight rings for the least number of moves to another rod. At a time, only one ring is allowed to carry, and you can not put a larger ring on less.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

icon: source/res/icon.png

apps:
  hanoi-towers:
    command: bin/hanoi-towers
#    desktop: usr/share/applications/desc.desktop
    plugs: [desktop, unity7, home, opengl, x11, wayland]
    environment:
      LD_LIBRARY_PATH: $SNAP/lib
      QML_IMPORT_PATH: $SNAP/qml
      QML2_IMPORT_PATH: $SNAP/qml
      QT_PLUGIN_PATH: $SNAP/plugins
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/plugins/platforms

parts:
  hanoi-towers:
    plugin: dump
    source: .


```
