### ISSUE TITLE
snap

### ISSUE THREAD

**Issue by EndrII** [QuasarApp/Hanoi-Towers#21]
при таком конфиге удается создать снап пакет
но при запуске и рисуется окно 
```
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/1000/snap.hanoi-tower', please create it with 0700 permissions.
libGL error: unable to load driver: r600_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: r600
libGL error: unable to load driver: r600_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: r600
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
Unrecognized OpenGL version
Unrecognized OpenGL version
QGLXContext: Failed to create dummy context
qrc:/main.qml:16: TypeError: Property 'launch' of object QQuickPage(0x5569fd4ccf40) is not a function
XmbTextListToTextProperty result code -2
Unrecognized OpenGL version
Unrecognized OpenGL version

```

```yaml
name: hanoi-tower
version: '1.5snap'
summary: Deploy Qt Project
description: |
  The Hanoi Tower is one of the most popular puzzles of the 19th century. |
  Three bars are given, on one of which eight rings are strung, the rings differ in size and lie smaller on larger ones.|
  The problem is to transfer the pyramid from eight rings for the least number of moves to another rod.|
  At a time, only one ring is allowed to carry, and you can not put a larger ring on less.|

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

icon: snap/gui/icon.png

apps:
  hanoi-tower:
    command: bin/hanoi-towers

    plugs: [desktop, unity7, home, opengl, x11, wayland]
    environment:
      LD_LIBRARY_PATH: $SNAP/lib
      QML_IMPORT_PATH: $SNAP/qml
      QML2_IMPORT_PATH: $SNAP/qml
      QT_PLUGIN_PATH: $SNAP/plugins
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/plugins/platforms


parts:
  hanoi-tower:
    plugin: dump
    source: app/

    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - libx11-xcb-dev
      - libglu1-mesa-dev
      - libxrender-dev
      - libxi-dev
      - libegl1-mesa
      - fontconfig


```
